import type { Metadata } from "next";
import { Vazirmatn, Lalezar, Cairo } from "next/font/google";
import "./globals.css";

const vazirmatn = Vazirmatn({
  subsets: ["arabic"],
  weight: "400",
  variable: "--font-vazir",
  display: "swap",
});
const lalezar = Lalezar({
  subsets: ["arabic"],
  weight: "400",
  variable: "--font-lalezar",
  display: "swap",
});
const cairo = Cairo({
  subsets: ["arabic"],
  weight: ["600", "700", "500"],
  variable: "--font-cairo",
  display: "optional",
});
export const metadata: Metadata = {
  title: "Poshakino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${lalezar.variable} ${vazirmatn.variable} ${cairo.variable}h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
